# Generated by Django 2.2.9 on 2020-03-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='org_building_name_no',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='org_county',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='org_postcode',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='org_street',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='org_town',
        ),
    ]
