# Generated by Django 2.2.9 on 2020-03-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200319_2257'),
        ('fenlandlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Client'),
        ),
    ]
