# Generated by Django 2.2.9 on 2020-03-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenlandlp', '0004_auto_20200321_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
